name: Bump Package Version

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Version Number
        default: v1.0.0
        required: true

jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - run: git config --global user.name ${{ secrets.GH_USERNAME }}
      - run: git config --global user.email ${{ secrets.GH_EMAIL }}
      - run: npm version ${{ github.event.inputs.version }} -m "[GIT-ACTION] bump package to ${{ github.event.inputs.version }}"
      - run: git push